// Liga Profesional Argentina — temporada 2025
export default {
  id: 'ar',
  name: 'Liga Profesional',
  country: 'Argentina',
  // Todos los equipos de la máxima categoría, en orden alfabético por nombre.
  teams: [
    'ar_ald', 'ar_aaj', 'ar_atu', 'ar_ban', 'ar_bac', 'ar_blg', 'boca', 'ar_ccsde',
    'ar_dyj', 'ar_rie', 'est', 'ar_glp', 'ar_gcz', 'ar_hur', 'ind', 'ar_irv',
    'ar_ins', 'ar_lan', 'ar_nob', 'ar_pla', 'rac', 'river', 'ar_rce', 'slo',
    'ar_smsj', 'ar_sar', 'ar_tal', 'ar_tig', 'ar_usf', 'vel',
  ],
  // Equipos que no existían en el juego.
  newTeams: [
    {
      id: 'ar_ald',
      name: 'Aldosivi',
      short: 'ALD',
      kit:  { shirt: '#0f8a3c', alt2: '#f7d117', pattern: 'stripes', shorts: '#0f8a3c' },
      away: { shirt: '#ffffff', alt2: '#0f8a3c', pattern: 'band', shorts: '#ffffff' },
      squad: ['Carranza', 'Gino', 'Breitenbruch', 'Valentini', 'Villarreal', 'Serrago', 'Cerato', 'Román', 'Cabral', 'Guzmán', 'Ríos'],
      stadium: { name: 'Estadio José María Minella', city: 'Mar del Plata', seats: ['#0f8a3c', '#f7d117'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'ALDOSIVI', sky: 'night', features: [] },
    },
    {
      id: 'ar_aaj',
      name: 'Argentinos Juniors',
      short: 'AAJ',
      kit:  { shirt: '#d0202e', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#d0202e', pattern: 'sash', shorts: '#ffffff' },
      squad: ['Rodríguez', 'Prieto', 'Godoy', 'Torrén', 'Lozano', 'Lescano', 'Fattori', 'Oroz', 'López Muñoz', 'Viveros', 'Molina'],
      stadium: { name: 'Estadio Diego Armando Maradona', city: 'Buenos Aires', seats: ['#d0202e', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'EL BICHO', sky: 'night', features: [] },
    },
    {
      id: 'ar_atu',
      name: 'Atlético Tucumán',
      short: 'ATU',
      kit:  { shirt: '#7cc4ea', alt2: '#ffffff', pattern: 'stripes', shorts: '#13254a' },
      away: { shirt: '#13254a', alt2: '#7cc4ea', pattern: 'plain', shorts: '#13254a' },
      squad: ['Durso', 'Ferreira', 'Ferrari', 'Romero', 'Infante', 'Ruiz', 'Ortiz', 'Sánchez', 'Nicola', 'Díaz', 'Coronel'],
      stadium: { name: 'Monumental José Fierro', city: 'San Miguel de Tucumán', seats: ['#7cc4ea', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'DECANO', sky: 'night', features: [] },
    },
    {
      id: 'ar_ban',
      name: 'Banfield',
      short: 'BAN',
      kit:  { shirt: '#ffffff', alt2: '#0a7a3b', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#0a7a3b', alt2: '#ffffff', pattern: 'plain', shorts: '#0a7a3b' },
      squad: ['Sanguinetti', 'Abraham', 'Vittor', 'Maldonado', 'Ríos', 'Méndez', 'Palacios', 'Sosa', 'Soraire', 'Auzmendi', 'Sepúlveda'],
      stadium: { name: 'Estadio Florencio Sola', city: 'Banfield', seats: ['#0a7a3b', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'BANFIELD', sky: 'night', features: [] },
    },
    {
      id: 'ar_bac',
      name: 'Barracas Central',
      short: 'BAC',
      kit:  { shirt: '#d81e2a', alt2: '#ffffff', pattern: 'stripes', shorts: '#d81e2a' },
      away: { shirt: '#ffffff', alt2: '#d81e2a', pattern: 'band', shorts: '#ffffff' },
      squad: ['Miño', 'Capraro', 'Tobio', 'Cabral', 'Jappert', 'Insúa', 'Miloc', 'Tapia', 'Mazzola', 'Bruera', 'Candia'],
      stadium: { name: 'Estadio Claudio Chiqui Tapia', city: 'Buenos Aires', seats: ['#d81e2a', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'checks', letters: 'EL GUAPO', sky: 'night', features: [] },
    },
    {
      id: 'ar_blg',
      name: 'Belgrano',
      short: 'BLG',
      kit:  { shirt: '#6ab4e4', alt2: '#ffffff', pattern: 'plain', shorts: '#0f1c3a' },
      away: { shirt: '#0f1c3a', alt2: '#6ab4e4', pattern: 'plain', shorts: '#0f1c3a' },
      squad: ['Cardozo', 'Ricca', 'López', 'Morales', 'Meriano', 'Fernández', 'Saravia', 'Zelarayán', 'Heredia', 'Passerini', 'Jara'],
      stadium: { name: 'Gigante de Alberdi', city: 'Córdoba', seats: ['#6ab4e4', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'PIRATA', sky: 'night', features: [] },
    },
    {
      id: 'ar_ccsde',
      name: 'Central Córdoba',
      short: 'CCO',
      kit:  { shirt: '#ffffff', alt2: '#111111', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#c8102e', alt2: '#111111', pattern: 'plain', shorts: '#111111' },
      squad: ['Aguerre', 'Iberbia', 'Maldonado', 'Martínez', 'Florentín', 'Soraire', 'Barrios', 'Moreyra', 'Heredia', 'Varaldo', 'Perea'],
      stadium: { name: 'Estadio Madre de Ciudades', city: 'Santiago del Estero', seats: ['#111111', '#ffffff'], track: null, roof: '#d8dce0', shape: 'round', mow: 'stripes', letters: 'FERROVIARIO', sky: 'night', features: [] },
    },
    {
      id: 'ar_dyj',
      name: 'Defensa y Justicia',
      short: 'DYJ',
      kit:  { shirt: '#f5d10f', alt2: '#0a7a3b', pattern: 'plain', shorts: '#0a7a3b' },
      away: { shirt: '#0a7a3b', alt2: '#f5d10f', pattern: 'plain', shorts: '#0a7a3b' },
      squad: ['Fiermarin', 'Fernández', 'Cáceres', 'Lisandrini', 'Barbieri', 'Miritello', 'Molinas', 'Galdames', 'Bogarín', 'Osorio', 'Tarragona'],
      stadium: { name: 'Estadio Norberto Tomaghello', city: 'Florencio Varela', seats: ['#f5d10f', '#0a7a3b'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'EL HALCON', sky: 'night', features: [] },
    },
    {
      id: 'ar_rie',
      name: 'Deportivo Riestra',
      short: 'RIE',
      kit:  { shirt: '#111111', alt2: '#ffffff', pattern: 'plain', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#111111', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Arce', 'Sosa', 'Paz', 'Benegas', 'Monje', 'Céliz', 'Goitea', 'Ramírez', 'Fernández', 'Herrera', 'Díaz'],
      stadium: { name: 'Estadio Guillermo Laza', city: 'Buenos Aires', seats: ['#111111', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'checks', letters: 'MALEVO', sky: 'night', features: [] },
    },
    {
      id: 'ar_glp',
      name: 'Gimnasia y Esgrima La Plata',
      short: 'GLP',
      kit:  { shirt: '#ffffff', alt2: '#13254a', pattern: 'band', shorts: '#ffffff' },
      away: { shirt: '#13254a', alt2: '#ffffff', pattern: 'band', shorts: '#13254a' },
      squad: ['Insfrán', 'Melluso', 'Morales', 'Silva Torrejón', 'Enrique', 'Panaro', 'Max', 'Barros', 'Steimbach', 'Torres', 'Hurtado'],
      stadium: { name: 'Estadio Juan Carmelo Zerillo', city: 'La Plata', seats: ['#13254a', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'EL LOBO', sky: 'night', features: [] },
    },
    {
      id: 'ar_gcz',
      name: 'Godoy Cruz',
      short: 'GCZ',
      kit:  { shirt: '#1c4fa0', alt2: '#ffffff', pattern: 'stripes', shorts: '#1c4fa0' },
      away: { shirt: '#ffffff', alt2: '#1c4fa0', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Petroli', 'Arce', 'Rasmussen', 'Barrios', 'Bersano', 'Andino', 'Leyes', 'Abrego', 'Bustos', 'Rodríguez', 'Barrea'],
      stadium: { name: 'Estadio Malvinas Argentinas', city: 'Mendoza', seats: ['#1c4fa0', '#ffffff'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'EL TOMBA', sky: 'dusk', features: ['andes'] },
    },
    {
      id: 'ar_hur',
      name: 'Huracán',
      short: 'HUR',
      kit:  { shirt: '#ffffff', alt2: '#d0202e', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#d0202e', alt2: '#ffffff', pattern: 'plain', shorts: '#d0202e' },
      squad: ['Galíndez', 'Benítez', 'Carrizo', 'Pereyra', 'Ibáñez', 'Cabral', 'Ojeda', 'Gil', 'Mazzantti', 'Ramírez', 'Caicedo'],
      stadium: { name: 'Estadio Tomás Adolfo Ducó', city: 'Buenos Aires', seats: ['#d0202e', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'HURACAN', sky: 'night', features: ['tower'] },
    },
    {
      id: 'ar_irv',
      name: 'Independiente Rivadavia',
      short: 'IRV',
      kit:  { shirt: '#1b3f94', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#1b3f94', pattern: 'sash', shorts: '#1b3f94' },
      squad: ['Centurión', 'Costa', 'Studer', 'Gómez', 'Bonifacio', 'Villa', 'Elordi', 'Fernández', 'Sartori', 'Arce', 'Retamar'],
      stadium: { name: 'Estadio Bautista Gargantini', city: 'Mendoza', seats: ['#1b3f94', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'LA LEPRA', sky: 'dusk', features: ['andes'] },
    },
    {
      id: 'ar_ins',
      name: 'Instituto',
      short: 'INS',
      kit:  { shirt: '#ffffff', alt2: '#d0202e', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#111111', alt2: '#d0202e', pattern: 'plain', shorts: '#111111' },
      squad: ['Roffo', 'Rodríguez', 'Alarcón', 'Franco', 'Jara', 'Acevedo', 'Lodico', 'Fernández', 'Zalazar', 'Puebla', 'Romero'],
      stadium: { name: 'Monumental de Alta Córdoba', city: 'Córdoba', seats: ['#d0202e', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'LA GLORIA', sky: 'night', features: [] },
    },
    {
      id: 'ar_lan',
      name: 'Lanús',
      short: 'LAN',
      kit:  { shirt: '#6e1a2c', alt2: '#ffffff', pattern: 'plain', shorts: '#6e1a2c' },
      away: { shirt: '#ffffff', alt2: '#6e1a2c', pattern: 'band', shorts: '#ffffff' },
      squad: ['Losada', 'Marcich', 'Izquierdoz', 'Canale', 'Guidara', 'Moreno', 'Medina', 'Cardozo', 'Salvio', 'Bou', 'Castillo'],
      stadium: { name: 'Estadio Ciudad de Lanús', city: 'Lanús', seats: ['#6e1a2c', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'GRANATE', sky: 'night', features: [] },
    },
    {
      id: 'ar_nob',
      name: 'Newell\'s Old Boys',
      short: 'NOB',
      kit:  { shirt: '#d0202e', alt2: '#111111', pattern: 'sleeves', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#d0202e', pattern: 'center', shorts: '#111111' },
      squad: ['Navas', 'Martino', 'Salcedo', 'Velázquez', 'Méndez', 'Herrera', 'Banega', 'Fernández', 'Silvetti', 'Ramírez', 'Cóccaro'],
      stadium: { name: 'Estadio Marcelo Bielsa', city: 'Rosario', seats: ['#d0202e', '#111111'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'LA LEPRA', sky: 'night', features: [] },
    },
    {
      id: 'ar_pla',
      name: 'Platense',
      short: 'PLA',
      kit:  { shirt: '#ffffff', alt2: '#5a3520', pattern: 'band', shorts: '#5a3520' },
      away: { shirt: '#5a3520', alt2: '#ffffff', pattern: 'band', shorts: '#5a3520' },
      squad: ['Cozzani', 'Lozano', 'Vázquez', 'Salomón', 'Saborido', 'Taborda', 'Picco', 'Zapiola', 'Mainero', 'Martínez', 'Lotti'],
      stadium: { name: 'Estadio Ciudad de Vicente López', city: 'Florida', seats: ['#5a3520', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'checks', letters: 'CALAMAR', sky: 'night', features: [] },
    },
    {
      id: 'ar_rce',
      name: 'Rosario Central',
      short: 'RCE',
      kit:  { shirt: '#1d3f8c', alt2: '#f5c518', pattern: 'stripes', shorts: '#1d3f8c' },
      away: { shirt: '#f5c518', alt2: '#1d3f8c', pattern: 'plain', shorts: '#f5c518' },
      squad: ['Broun', 'Sández', 'Komar', 'Quintana', 'Coronel', 'Campaz', 'Ibarra', 'Malcorra', 'Di María', 'Copetti', 'Véliz'],
      stadium: { name: 'Gigante de Arroyito', city: 'Rosario', seats: ['#1d3f8c', '#f5c518'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'CANALLA', sky: 'night', features: [] },
    },
    {
      id: 'ar_smsj',
      name: 'San Martín de San Juan',
      short: 'SMJ',
      kit:  { shirt: '#0a7a3b', alt2: '#111111', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#0a7a3b', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Borgogno', 'Díaz', 'Pellegrino', 'Recalde', 'Jaurena', 'Rodríguez', 'Watson', 'Moreno', 'Olivera', 'Sánchez', 'Mónaco'],
      stadium: { name: 'Estadio Ingeniero Hilario Sánchez', city: 'San Juan', seats: ['#0a7a3b', '#111111'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'SAN MARTIN', sky: 'dusk', features: ['andes'] },
    },
    {
      id: 'ar_sar',
      name: 'Sarmiento',
      short: 'SAR',
      kit:  { shirt: '#0a8a3e', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#0a8a3e', pattern: 'band', shorts: '#ffffff' },
      squad: ['Acosta', 'Montoya', 'Insaurralde', 'Giménez', 'Mansilla', 'Andrada', 'Vera', 'Gaibor', 'Gondou', 'Magnín', 'Morales'],
      stadium: { name: 'Estadio Eva Perón', city: 'Junín', seats: ['#0a8a3e', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'SARMIENTO', sky: 'night', features: [] },
    },
    {
      id: 'ar_tal',
      name: 'Talleres',
      short: 'TAL',
      kit:  { shirt: '#ffffff', alt2: '#13254a', pattern: 'stripes', shorts: '#13254a' },
      away: { shirt: '#13254a', alt2: '#ffffff', pattern: 'plain', shorts: '#13254a' },
      squad: ['Herrera', 'Riveros', 'Catalán', 'Ramírez', 'Benavídez', 'Botta', 'Ortegoza', 'Galarza', 'Rick', 'Girotti', 'Bustos'],
      stadium: { name: 'Estadio Mario Alberto Kempes', city: 'Córdoba', seats: ['#13254a', '#ffffff'], track: '#c8552c', roof: null, shape: 'round', mow: 'stripes', letters: 'LA T', sky: 'night', features: [] },
    },
    {
      id: 'ar_tig',
      name: 'Tigre',
      short: 'TIG',
      kit:  { shirt: '#14306e', alt2: '#d0202e', pattern: 'band', shorts: '#14306e' },
      away: { shirt: '#ffffff', alt2: '#d0202e', pattern: 'band', shorts: '#ffffff' },
      squad: ['Zenobio', 'Cabral', 'Laso', 'Paz', 'Rizzo', 'Armoa', 'Saralegui', 'Prediger', 'Fernández', 'Russo', 'Romero'],
      stadium: { name: 'Estadio José Dellagiovanna', city: 'Victoria', seats: ['#14306e', '#d0202e'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'EL MATADOR', sky: 'night', features: [] },
    },
    {
      id: 'ar_usf',
      name: 'Unión',
      short: 'USF',
      kit:  { shirt: '#d0202e', alt2: '#ffffff', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#d0202e', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Tagliamonte', 'Del Blanco', 'Paz', 'Pardo', 'Vargas', 'Palacios', 'Pittón', 'Mosqueira', 'Estigarribia', 'Morales', 'Colazo'],
      stadium: { name: 'Estadio 15 de Abril', city: 'Santa Fe', seats: ['#d0202e', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'TATENGUE', sky: 'night', features: [] },
    },
  ],
};
