// Brasileirão Série A 2025 (temporada calendario 2025)
export default {
  id: 'br',
  name: 'Brasileirão',
  country: 'Brasil',
  // Todos los equipos de la máxima categoría, en orden alfabético por nombre.
  teams: [
    'br_cam', 'br_bah', 'br_bot', 'br_cea', 'cor', 'br_cru', 'fla', 'br_flu', 'br_for', 'br_gre',
    'br_sci', 'br_juv', 'br_mir', 'pal', 'br_rbb', 'br_sfc', 'sao', 'br_spt', 'br_vas', 'br_vit',
  ],
  // Equipos que no existían en el juego.
  newTeams: [
    {
      id: 'br_cam', name: 'Atlético Mineiro', short: 'CAM',
      kit:  { shirt: '#111111', alt2: '#ffffff', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#111111', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Everson', 'Arana', 'Alonso', 'Lyanco', 'Natanael', 'Scarpa', 'Alan Franco', 'Fausto Vera', 'Bernard', 'Hulk', 'Rony'],
      stadium: { name: 'Arena MRV', city: 'Belo Horizonte', seats: ['#111111', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'GALO', sky: 'night', features: [] },
    },
    {
      id: 'br_bah', name: 'Bahia', short: 'BAH',
      kit:  { shirt: '#ffffff', alt2: '#0047ab', pattern: 'band', shorts: '#0047ab' },
      away: { shirt: '#0047ab', alt2: '#d7182a', pattern: 'stripes', shorts: '#ffffff' },
      squad: ['M. Felipe', 'Juba', 'David Duarte', 'Kanu', 'Gilberto', 'Jean Lucas', 'Caio', 'E. Ribeiro', 'Erick Pulga', 'Willian José', 'Ademir'],
      stadium: { name: 'Arena Fonte Nova', city: 'Salvador', seats: ['#0047ab', '#d7182a'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'BAHIA', sky: 'night', features: [] },
    },
    {
      id: 'br_bot', name: 'Botafogo', short: 'BOT',
      kit:  { shirt: '#111111', alt2: '#ffffff', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#111111', pattern: 'plain', shorts: '#ffffff' },
      squad: ['John', 'Alex Telles', 'Barboza', 'Bastos', 'Vitinho', 'Artur', 'Marlon', 'Newton', 'Savarino', 'Cabral', 'Correa'],
      stadium: { name: 'Estádio Nilton Santos', city: 'Río de Janeiro', seats: ['#111111', '#ffffff'], track: '#c8552c', roof: null, shape: 'rect', mow: 'stripes', letters: 'FOGAO', sky: 'night', features: [] },
    },
    {
      id: 'br_cea', name: 'Ceará', short: 'CEA',
      kit:  { shirt: '#111111', alt2: '#ffffff', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#111111', pattern: 'plain', shorts: '#ffffff' },
      squad: ['B. Ferreira', 'M. Bahia', 'Marllon', 'W. Machado', 'Fabiano', 'Lourenço', 'Dieguinho', 'Sobral', 'Galeano', 'Pedro Raul', 'Aylon'],
      stadium: { name: 'Arena Castelão', city: 'Fortaleza', seats: ['#111111', '#ffffff'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'VOVO', sky: 'night', features: [] },
    },
    {
      id: 'br_cru', name: 'Cruzeiro', short: 'CRU',
      kit:  { shirt: '#0033a0', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#0033a0', pattern: 'plain', shorts: '#0033a0' },
      squad: ['Cássio', 'Kaiki', 'Fabrício', 'Villalba', 'William', 'Christian', 'Romero', 'Lucas Silva', 'M. Pereira', 'Kaio Jorge', 'Gabigol'],
      stadium: { name: 'Mineirão', city: 'Belo Horizonte', seats: ['#0033a0', '#ffffff'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'CRUZEIRO', sky: 'night', features: [] },
    },
    {
      id: 'br_flu', name: 'Fluminense', short: 'FLU',
      kit:  { shirt: '#8a1538', alt2: '#00613c', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#8a1538', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Fábio', 'Renê', 'Thiago Silva', 'Freytes', 'Samuel', 'Hércules', 'Martinelli', 'Nonato', 'Canobbio', 'Arias', 'Cano'],
      stadium: { name: 'Maracanã', city: 'Río de Janeiro', seats: ['#8a1538', '#00613c'], track: null, roof: '#e6e6e6', shape: 'round', mow: 'stripes', letters: 'FLUMINENSE', sky: 'night', features: [] },
    },
    {
      id: 'br_for', name: 'Fortaleza', short: 'FOR',
      kit:  { shirt: '#d71920', alt2: '#0b3d91', pattern: 'hoops', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#0b3d91', pattern: 'band', shorts: '#ffffff' },
      squad: ['João Ricardo', 'Pacheco', 'Brítez', 'Kuscevic', 'Tinga', 'Pochettino', 'Lucas Sasha', 'Martínez', 'Marinho', 'Lucero', 'Breno Lopes'],
      stadium: { name: 'Arena Castelão', city: 'Fortaleza', seats: ['#d71920', '#0b3d91'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'LEAO', sky: 'night', features: [] },
    },
    {
      id: 'br_gre', name: 'Grêmio', short: 'GRE',
      kit:  { shirt: '#0d80bf', alt2: '#111111', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#0d80bf', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Volpi', 'Marlon', 'Kannemann', 'Balbuena', 'João Pedro', 'Edenílson', 'Dodi', 'Villasanti', 'Cristaldo', 'Braithwaite', 'C. Vinícius'],
      stadium: { name: 'Arena do Grêmio', city: 'Porto Alegre', seats: ['#0d80bf', '#111111'], track: null, roof: '#e6e6e6', shape: 'rect', mow: 'stripes', letters: 'GREMIO', sky: 'night', features: [] },
    },
    {
      id: 'br_sci', name: 'Internacional', short: 'SCI',
      kit:  { shirt: '#e2001a', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#e2001a', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Rochet', 'Bernabei', 'Vitão', 'Mercado', 'Aguirre', 'Wesley', 'Thiago Maia', 'Fernando', 'Alan Patrick', 'Valencia', 'Borré'],
      stadium: { name: 'Estádio Beira-Rio', city: 'Porto Alegre', seats: ['#e2001a', '#ffffff'], track: null, roof: '#e6e6e6', shape: 'round', mow: 'stripes', letters: 'COLORADO', sky: 'night', features: [] },
    },
    {
      id: 'br_juv', name: 'Juventude', short: 'JVT',
      kit:  { shirt: '#ffffff', alt2: '#00843d', pattern: 'stripes', shorts: '#00843d' },
      away: { shirt: '#00843d', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Gustavo', 'Marcos Paulo', 'Abner', 'Rodrigo Sam', 'Ewerthon', 'Jadson', 'Caíque', 'Mandaca', 'Nenê', 'Gilberto', 'Batalla'],
      stadium: { name: 'Estádio Alfredo Jaconi', city: 'Caxias do Sul', seats: ['#00843d', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'JUVENTUDE', sky: 'dusk', features: [] },
    },
    {
      id: 'br_mir', name: 'Mirassol', short: 'MIR',
      kit:  { shirt: '#f7d117', alt2: '#00843d', pattern: 'plain', shorts: '#00843d' },
      away: { shirt: '#00843d', alt2: '#f7d117', pattern: 'plain', shorts: '#00843d' },
      squad: ['Walter', 'Reinaldo', 'Jemmes', 'João Victor', 'Lucas Ramon', 'Negueba', 'Neto Moura', 'José Aldo', 'Danielzinho', 'Chico', 'Carioca'],
      stadium: { name: 'Estádio Maião', city: 'Mirassol', seats: ['#f7d117', '#00843d'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'MIRASSOL', sky: 'day', features: [] },
    },
    {
      id: 'br_rbb', name: 'Red Bull Bragantino', short: 'RBB',
      kit:  { shirt: '#ffffff', alt2: '#d6001c', pattern: 'band', shorts: '#1b2a5c' },
      away: { shirt: '#1b2a5c', alt2: '#d6001c', pattern: 'plain', shorts: '#1b2a5c' },
      squad: ['Cleiton', 'Capixaba', 'P. Henrique', 'Guzmán', 'Hurtado', 'Jhon Jhon', 'Gabriel', 'Eric Ramires', 'Lincoln', 'Sasha', 'Pitta'],
      stadium: { name: 'Estádio Nabi Abi Chedid', city: 'Bragança Paulista', seats: ['#d6001c', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'BRAGANTINO', sky: 'night', features: [] },
    },
    {
      id: 'br_sfc', name: 'Santos', short: 'SFC',
      kit:  { shirt: '#ffffff', alt2: '#111111', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#111111', alt2: '#ffffff', pattern: 'stripes', shorts: '#111111' },
      squad: ['Brazão', 'Escobar', 'Luan Peres', 'Zé Ivaldo', 'Igor', 'Rollheiser', 'Zé Rafael', 'Rincón', 'Barreal', 'Neymar', 'Guilherme'],
      stadium: { name: 'Vila Belmiro', city: 'Santos', seats: ['#ffffff', '#111111'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'SANTOS', sky: 'night', features: [] },
    },
    {
      id: 'br_spt', name: 'Sport Recife', short: 'SPT',
      kit:  { shirt: '#d7182a', alt2: '#111111', pattern: 'hoops', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#d7182a', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Vasconcelos', 'Igor Cariús', 'Ramon', 'Thyere', 'M. Alexandre', 'Barletta', 'Rivera', 'Zé Lucas', 'Lucas Lima', 'Pablo', 'Paciência'],
      stadium: { name: 'Ilha do Retiro', city: 'Recife', seats: ['#d7182a', '#111111'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'SPORT', sky: 'night', features: [] },
    },
    {
      id: 'br_vas', name: 'Vasco da Gama', short: 'VAS',
      kit:  { shirt: '#ffffff', alt2: '#111111', pattern: 'sash', shorts: '#111111' },
      away: { shirt: '#111111', alt2: '#ffffff', pattern: 'sash', shorts: '#111111' },
      squad: ['Léo Jardim', 'Piton', 'L. Freitas', 'Robert Renan', 'P. Henrique', 'Nuno Moreira', 'Hugo Moura', 'T. Mendes', 'Coutinho', 'Rayan', 'Vegetti'],
      stadium: { name: 'São Januário', city: 'Río de Janeiro', seats: ['#111111', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'VASCO', sky: 'night', features: [] },
    },
    {
      id: 'br_vit', name: 'Vitória', short: 'VIT',
      kit:  { shirt: '#d7182a', alt2: '#111111', pattern: 'hoops', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#d7182a', pattern: 'plain', shorts: '#111111' },
      squad: ['Arcanjo', 'Jamerson', 'Halter', 'Neris', 'Cáceres', 'Matheuzinho', 'Ronald', 'W. Oliveira', 'Erick', 'Kayzer', 'Osvaldo'],
      stadium: { name: 'Barradão', city: 'Salvador', seats: ['#d7182a', '#111111'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'VITORIA', sky: 'night', features: [] },
    },
  ],
};
