// Liga de Primera 2025 (temporada calendario)
export default {
  id: 'cl',
  name: 'Primera de Chile',
  country: 'Chile',
  // Todos los equipos de la máxima categoría, en orden alfabético por nombre.
  teams: ['cl_aud', 'cl_csl', 'colo', 'cl_cqu', 'cl_iqq', 'cl_lsr', 'cl_lmc', 'cl_evv', 'cl_huc', 'cl_nub', 'cl_ohi', 'cl_pst', 'udch', 'cl_ues', 'cl_ulc', 'uc'],
  // Equipos que no existían en el juego.
  newTeams: [
    {
      id: 'cl_aud',
      name: 'Audax Italiano',
      short: 'AUD',
      kit: { shirt: '#0a7a3c', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#0a7a3c', pattern: 'plain', shorts: '#0a7a3c' },
      squad: ['Ahumada', 'Tapia', 'Lobos', 'Jara', 'Guerra', 'Bahamonde', 'Fuentes', 'Fernández', 'Mazzantti', 'Palacios', 'Benegas'],
      stadium: { name: 'Estadio Bicentenario de La Florida', city: 'Santiago', seats: ['#0a7a3c', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'AUDAX', sky: 'night', features: ['andes'] },
    },
    {
      id: 'cl_csl',
      name: 'Cobresal',
      short: 'CSL',
      kit: { shirt: '#f26a1b', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#f26a1b', pattern: 'plain', shorts: '#f26a1b' },
      squad: ['Santander', 'Moreno', 'Clavijo', 'Jorquera', 'González', 'Valencia', 'Ramírez', 'Torres', 'Rivas', 'Coelho', 'Pino'],
      stadium: { name: 'Estadio El Cobre', city: 'El Salvador', seats: ['#f26a1b', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'MINEROS', sky: 'day', features: ['andes'] },
    },
    {
      id: 'cl_cqu',
      name: 'Coquimbo Unido',
      short: 'CQU',
      kit: { shirt: '#f7c600', alt2: '#111111', pattern: 'plain', shorts: '#111111' },
      away: { shirt: '#111111', alt2: '#f7c600', pattern: 'plain', shorts: '#111111' },
      squad: ['Sánchez', 'Cornejo', 'Fernández', 'Salinas', 'Azócar', 'Bechtholdt', 'Galani', 'Camargo', 'Zavala', 'Johansen', 'Waterman'],
      stadium: { name: 'Estadio Francisco Sánchez Rumoroso', city: 'Coquimbo', seats: ['#f7c600', '#1a1a1a'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'PIRATAS', sky: 'dusk', features: [] },
    },
    {
      id: 'cl_iqq',
      name: 'Deportes Iquique',
      short: 'IQQ',
      kit: { shirt: '#5fb4e5', alt2: '#ffffff', pattern: 'plain', shorts: '#5fb4e5' },
      away: { shirt: '#ffffff', alt2: '#5fb4e5', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Requena', 'Cerda', 'Bonifacio', 'Carrasco', 'Fernández', 'Puch', 'Pino', 'Barrera', 'Llanos', 'Ramos', 'Rabello'],
      stadium: { name: 'Estadio Tierra de Campeones', city: 'Iquique', seats: ['#5fb4e5', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'DRAGONES', sky: 'day', features: [] },
    },
    {
      id: 'cl_lsr',
      name: 'Deportes La Serena',
      short: 'LSR',
      kit: { shirt: '#7a1f2b', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#7a1f2b', pattern: 'plain', shorts: '#7a1f2b' },
      squad: ['Lanzillota', 'Acevedo', 'Monzón', 'Navarrete', 'Vegas', 'Araya', 'Herrera', 'Leyes', 'Guerra', 'Montecinos', 'Mateos'],
      stadium: { name: 'Estadio La Portada', city: 'La Serena', seats: ['#7a1f2b', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'GRANATES', sky: 'dusk', features: [] },
    },
    {
      id: 'cl_lmc',
      name: 'Deportes Limache',
      short: 'LMC',
      kit: { shirt: '#c8102e', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#c8102e', pattern: 'plain', shorts: '#c8102e' },
      squad: ['Bórquez', 'Ramírez', 'Ovelar', 'Hernández', 'Puebla', 'Ortiz', 'Valenzuela', 'Morales', 'Vargas', 'Castro', 'Cuevas'],
      stadium: { name: 'Estadio Lucio Fariña', city: 'Quillota', seats: ['#c8102e', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'TOMATEROS', sky: 'night', features: [] },
    },
    {
      id: 'cl_evv',
      name: 'Everton',
      short: 'EVV',
      kit: { shirt: '#1f3f8f', alt2: '#f2b705', pattern: 'stripes', shorts: '#1f3f8f' },
      away: { shirt: '#f2b705', alt2: '#1f3f8f', pattern: 'plain', shorts: '#1f3f8f' },
      squad: ['González', 'Rojas', 'Pineda', 'Salgado', 'Berríos', 'Méndez', 'Ulloa', 'Montes', 'Lescano', 'Altamirano', 'Contreras'],
      stadium: { name: 'Estadio Sausalito', city: 'Viña del Mar', seats: ['#1f3f8f', '#f2b705'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'EVERTON', sky: 'dusk', features: [] },
    },
    {
      id: 'cl_huc',
      name: 'Huachipato',
      short: 'HUC',
      kit: { shirt: '#1e4fa0', alt2: '#111111', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#1e4fa0', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Castellón', 'Caroca', 'Ramírez', 'Mardones', 'Gutiérrez', 'Martínez', 'Sepúlveda', 'Montes', 'Altamirano', 'Rodríguez', 'Silva'],
      stadium: { name: 'Estadio Huachipato-CAP Acero', city: 'Talcahuano', seats: ['#1e4fa0', '#1a1a1a'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'ACEREROS', sky: 'night', features: [] },
    },
    {
      id: 'cl_nub',
      name: 'Ñublense',
      short: 'NUB',
      kit: { shirt: '#d1162b', alt2: '#ffffff', pattern: 'plain', shorts: '#d1162b' },
      away: { shirt: '#ffffff', alt2: '#d1162b', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Pérez', 'Jiménez', 'Roco', 'Rodríguez', 'Suazo', 'Vallejos', 'Reyes', 'Valencia', 'Gálvez', 'Rubio', 'Chandía'],
      stadium: { name: 'Estadio Nelson Oyarzún', city: 'Chillán', seats: ['#d1162b', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'DIABLOS ROJOS', sky: 'night', features: ['andes'] },
    },
    {
      id: 'cl_ohi',
      name: 'O\'Higgins',
      short: 'OHI',
      kit: { shirt: '#5bb3e4', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#5bb3e4', pattern: 'plain', shorts: '#5bb3e4' },
      squad: ['Carabalí', 'Meza', 'Fernández', 'Pino', 'Faúndez', 'González', 'Leiva', 'Sarrafiore', 'Hernández', 'Castillo', 'Rabello'],
      stadium: { name: 'Estadio El Teniente', city: 'Rancagua', seats: ['#5bb3e4', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'OHIGGINS', sky: 'night', features: ['andes'] },
    },
    {
      id: 'cl_pst',
      name: 'Palestino',
      short: 'PST',
      kit: { shirt: '#ffffff', alt2: '#00843d', pattern: 'center', shorts: '#111111' },
      away: { shirt: '#d1162b', alt2: '#00843d', pattern: 'plain', shorts: '#111111' },
      squad: ['Pérez', 'Garguez', 'Riveros', 'Roco', 'Carrasco', 'Villanueva', 'León', 'Cornejo', 'Abrigo', 'Davis', 'Benítez'],
      stadium: { name: 'Estadio Municipal de La Cisterna', city: 'Santiago', seats: ['#00843d', '#d1162b'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'PALESTINO', sky: 'night', features: ['andes'] },
    },
    {
      id: 'cl_ues',
      name: 'Unión Española',
      short: 'UES',
      kit: { shirt: '#c8102e', alt2: '#f7c600', pattern: 'plain', shorts: '#0b2c7a' },
      away: { shirt: '#ffffff', alt2: '#c8102e', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Parra', 'Hidalgo', 'Ahumada', 'Tapia', 'Gazzolo', 'Lagos', 'Pérez', 'Fuentes', 'Morales', 'Pinares', 'Di Yorio'],
      stadium: { name: 'Estadio Santa Laura', city: 'Santiago', seats: ['#c8102e', '#f7c600'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'HISPANOS', sky: 'night', features: ['andes'] },
    },
    {
      id: 'cl_ulc',
      name: 'Unión La Calera',
      short: 'ULC',
      kit: { shirt: '#e01a22', alt2: '#ffffff', pattern: 'plain', shorts: '#e01a22' },
      away: { shirt: '#ffffff', alt2: '#e01a22', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Avellaneda', 'Ocampo', 'Ugarte', 'Díaz', 'Sanhueza', 'Alarcón', 'Moya', 'Rodríguez', 'Ojeda', 'Sáez', 'Lara'],
      stadium: { name: 'Estadio Nicolás Chahuán Nazar', city: 'La Calera', seats: ['#e01a22', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'CEMENTEROS', sky: 'night', features: [] },
    },
  ],
};
