// Premier League 2025-26
export default {
  id: 'en',
  name: 'Premier League',
  country: 'Inglaterra',
  // Todos los equipos de la máxima categoría, en orden alfabético por nombre.
  teams: ['ars', 'en_avl', 'en_bou', 'en_bre', 'en_bha', 'en_bur', 'che', 'en_cry', 'en_eve', 'en_ful', 'en_lee', 'liv', 'mci', 'mun', 'new', 'en_nfo', 'en_sun', 'tot', 'en_whu', 'en_wol'],
  // Equipos que no existían en el juego.
  newTeams: [
    {
      id: 'en_avl',
      name: 'Aston Villa',
      short: 'AVL',
      kit:  { shirt: '#670e36', alt2: '#95bfe5', pattern: 'sleeves', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#670e36', pattern: 'plain', shorts: '#670e36' },
      squad: ['Martínez', 'Digne', 'Konsa', 'Torres', 'Cash', 'Rogers', 'Kamara', 'Tielemans', 'McGinn', 'Watkins', 'Buendía'],
      stadium: { name: 'Villa Park', city: 'Birmingham', seats: ['#670e36', '#95bfe5'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'VILLA', sky: 'night', features: ['kop'] },
    },
    {
      id: 'en_bou',
      name: 'Bournemouth',
      short: 'BOU',
      kit:  { shirt: '#da291c', alt2: '#000000', pattern: 'stripes', shorts: '#000000' },
      away: { shirt: '#ffffff', alt2: '#da291c', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Petrović', 'Truffert', 'Diakité', 'Senesi', 'Smith', 'Tavernier', 'Adams', 'Scott', 'Kluivert', 'Evanilson', 'Semenyo'],
      stadium: { name: 'Vitality Stadium', city: 'Bournemouth', seats: ['#da291c', '#000000'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'CHERRIES', sky: 'night', features: [] },
    },
    {
      id: 'en_bre',
      name: 'Brentford',
      short: 'BRE',
      kit:  { shirt: '#e30613', alt2: '#ffffff', pattern: 'stripes', shorts: '#000000' },
      away: { shirt: '#1b1b1b', alt2: '#e30613', pattern: 'plain', shorts: '#1b1b1b' },
      squad: ['Kelleher', 'Henry', 'Van den Berg', 'Collins', 'Kayode', 'Schade', 'Henderson', 'Jensen', 'Damsgaard', 'Thiago', 'Ouattara'],
      stadium: { name: 'Gtech Community Stadium', city: 'Londres', seats: ['#e30613', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'BEES', sky: 'night', features: [] },
    },
    {
      id: 'en_bha',
      name: 'Brighton',
      short: 'BHA',
      kit:  { shirt: '#0057b8', alt2: '#ffffff', pattern: 'stripes', shorts: '#0057b8' },
      away: { shirt: '#f5d200', alt2: '#0057b8', pattern: 'plain', shorts: '#0057b8' },
      squad: ['Verbruggen', 'Kadıoğlu', 'Dunk', 'Van Hecke', 'Wieffer', 'Mitoma', 'Baleba', 'Ayari', 'Minteh', 'Welbeck', 'Rutter'],
      stadium: { name: 'Amex Stadium', city: 'Brighton', seats: ['#0057b8', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'BRIGHTON', sky: 'night', features: ['trusses'] },
    },
    {
      id: 'en_bur',
      name: 'Burnley',
      short: 'BUR',
      kit:  { shirt: '#6c1d45', alt2: '#99d6ea', pattern: 'sleeves', shorts: '#ffffff' },
      away: { shirt: '#99d6ea', alt2: '#6c1d45', pattern: 'plain', shorts: '#99d6ea' },
      squad: ['Dúbravka', 'Hartman', 'Estève', 'Tuanzebe', 'Walker', 'Anthony', 'Cullen', 'Ugochukwu', 'Bruun Larsen', 'Flemming', 'Foster'],
      stadium: { name: 'Turf Moor', city: 'Burnley', seats: ['#6c1d45', '#99d6ea'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'CLARETS', sky: 'night', features: [] },
    },
    {
      id: 'en_cry',
      name: 'Crystal Palace',
      short: 'CRY',
      kit:  { shirt: '#1b458f', alt2: '#c4122e', pattern: 'stripes', shorts: '#1b458f' },
      away: { shirt: '#ffffff', alt2: '#c4122e', pattern: 'sash', shorts: '#ffffff' },
      squad: ['Henderson', 'Mitchell', 'Lacroix', 'Guéhi', 'Muñoz', 'Pino', 'Wharton', 'Kamada', 'Sarr', 'Mateta', 'Nketiah'],
      stadium: { name: 'Selhurst Park', city: 'Londres', seats: ['#1b458f', '#c4122e'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'EAGLES', sky: 'night', features: [] },
    },
    {
      id: 'en_eve',
      name: 'Everton',
      short: 'EVE',
      kit:  { shirt: '#003399', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#003399', pattern: 'plain', shorts: '#003399' },
      squad: ['Pickford', 'Mykolenko', 'Tarkowski', 'Keane', 'O\'Brien', 'Grealish', 'Gueye', 'Garner', 'Ndiaye', 'Barry', 'Dewsbury-Hall'],
      stadium: { name: 'Hill Dickinson Stadium', city: 'Liverpool', seats: ['#003399', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'EVERTON', sky: 'dusk', features: [] },
    },
    {
      id: 'en_ful',
      name: 'Fulham',
      short: 'FUL',
      kit:  { shirt: '#ffffff', alt2: '#000000', pattern: 'plain', shorts: '#000000' },
      away: { shirt: '#cc0000', alt2: '#000000', pattern: 'plain', shorts: '#cc0000' },
      squad: ['Leno', 'Robinson', 'Andersen', 'Bassey', 'Tete', 'Iwobi', 'Lukić', 'Berge', 'Wilson', 'Jiménez', 'Smith Rowe'],
      stadium: { name: 'Craven Cottage', city: 'Londres', seats: ['#ffffff', '#000000'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'FULHAM', sky: 'day', features: [] },
    },
    {
      id: 'en_lee',
      name: 'Leeds United',
      short: 'LEE',
      kit:  { shirt: '#ffffff', alt2: '#1d428a', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#1d428a', alt2: '#ffcd00', pattern: 'plain', shorts: '#1d428a' },
      squad: ['Perri', 'Gudmundsson', 'Rodon', 'Struijk', 'Bogle', 'Gnonto', 'Ampadu', 'Stach', 'Aaronson', 'Calvert-Lewin', 'Okafor'],
      stadium: { name: 'Elland Road', city: 'Leeds', seats: ['#ffffff', '#1d428a'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'LEEDS UNITED', sky: 'night', features: [] },
    },
    {
      id: 'en_nfo',
      name: 'Nottingham Forest',
      short: 'NFO',
      kit:  { shirt: '#dd0000', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#dd0000', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Sels', 'Williams', 'Milenković', 'Murillo', 'Aina', 'Hudson-Odoi', 'Anderson', 'Sangaré', 'Ndoye', 'Gibbs-White', 'Wood'],
      stadium: { name: 'City Ground', city: 'Nottingham', seats: ['#dd0000', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'FOREST', sky: 'night', features: [] },
    },
    {
      id: 'en_sun',
      name: 'Sunderland',
      short: 'SUN',
      kit:  { shirt: '#eb172b', alt2: '#ffffff', pattern: 'stripes', shorts: '#000000' },
      away: { shirt: '#14213d', alt2: '#eb172b', pattern: 'plain', shorts: '#14213d' },
      squad: ['Roefs', 'Reinildo', 'Ballard', 'Alderete', 'Mukiele', 'Le Fée', 'Xhaka', 'Sadiki', 'Talbi', 'Isidor', 'Brobbey'],
      stadium: { name: 'Stadium of Light', city: 'Sunderland', seats: ['#eb172b', '#ffffff'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'SUNDERLAND', sky: 'night', features: [] },
    },
    {
      id: 'en_whu',
      name: 'West Ham',
      short: 'WHU',
      kit:  { shirt: '#7a263a', alt2: '#1bb1e7', pattern: 'sleeves', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#7a263a', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Areola', 'Diouf', 'Todibo', 'Kilman', 'Wan-Bissaka', 'Summerville', 'Souček', 'Fernandes', 'Bowen', 'Paquetá', 'Wilson'],
      stadium: { name: 'London Stadium', city: 'Londres', seats: ['#7a263a', '#1bb1e7'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'WEST HAM', sky: 'night', features: [] },
    },
    {
      id: 'en_wol',
      name: 'Wolverhampton',
      short: 'WOL',
      kit:  { shirt: '#fdb913', alt2: '#000000', pattern: 'plain', shorts: '#000000' },
      away: { shirt: '#000000', alt2: '#fdb913', pattern: 'plain', shorts: '#000000' },
      squad: ['Sá', 'Bueno', 'Toti', 'Mosquera', 'Tchatchoua', 'Hwang', 'André', 'Gomes', 'Munetsi', 'Strand Larsen', 'Arokodare'],
      stadium: { name: 'Molineux', city: 'Wolverhampton', seats: ['#fdb913', '#000000'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'WOLVES', sky: 'night', features: [] },
    },
  ],
};
