// Serie A 2025-26
export default {
  id: 'it',
  name: 'Serie A',
  country: 'Italia',
  // Todos los equipos de la máxima categoría, en orden alfabético por nombre.
  teams: ['it_ata', 'it_bfc', 'it_cag', 'it_com', 'it_cre', 'it_fio', 'it_gen', 'it_hel', 'int', 'juv', 'it_laz', 'it_lec', 'mil', 'nap', 'it_prm', 'it_pis', 'rom', 'it_sas', 'it_tor', 'it_udi'],
  // Equipos que no existían en el juego.
  newTeams: [
    {
      id: 'it_ata',
      name: 'Atalanta',
      short: 'ATA',
      kit:  { shirt: '#1e71b8', alt2: '#000000', pattern: 'stripes', shorts: '#000000' },
      away: { shirt: '#ffffff', alt2: '#1e71b8', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Carnesecchi', 'Bernasconi', 'Hien', 'Djimsiti', 'Bellanova', 'Zalewski', 'De Roon', 'Ederson', 'Samardžić', 'Scamacca', 'De Ketelaere'],
      stadium: { name: 'New Balance Arena', city: 'Bérgamo', seats: ['#1e71b8', '#000000'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'ATALANTA', sky: 'night', features: [] },
    },
    {
      id: 'it_bfc',
      name: 'Bologna',
      short: 'BFC',
      kit:  { shirt: '#a21c26', alt2: '#1a2f48', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#a21c26', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Skorupski', 'Miranda', 'Lucumí', 'Heggem', 'Holm', 'Cambiaghi', 'Freuler', 'Pobega', 'Orsolini', 'Castro', 'Odgaard'],
      stadium: { name: 'Stadio Renato Dall\'Ara', city: 'Bolonia', seats: ['#a21c26', '#1a2f48'], track: '#c8552c', roof: null, shape: 'rect', mow: 'stripes', letters: 'BOLOGNA', sky: 'night', features: ['tower'] },
    },
    {
      id: 'it_cag',
      name: 'Cagliari',
      short: 'CAG',
      kit:  { shirt: '#a5001e', alt2: '#002350', pattern: 'stripes', shorts: '#002350' },
      away: { shirt: '#ffffff', alt2: '#a5001e', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Caprile', 'Obert', 'Mina', 'Luperto', 'Palestra', 'Luvumbo', 'Adopo', 'Prati', 'Folorunsho', 'Esposito', 'Borrelli'],
      stadium: { name: 'Unipol Domus', city: 'Cagliari', seats: ['#a5001e', '#002350'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'CAGLIARI', sky: 'dusk', features: [] },
    },
    {
      id: 'it_com',
      name: 'Como',
      short: 'COM',
      kit:  { shirt: '#1f5ba8', alt2: '#ffffff', pattern: 'plain', shorts: '#1f5ba8' },
      away: { shirt: '#ffffff', alt2: '#1f5ba8', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Butez', 'Valle', 'Ramón', 'Kempf', 'Smolčić', 'Kühn', 'Perrone', 'Da Cunha', 'Paz', 'Douvikas', 'Morata'],
      stadium: { name: 'Stadio Giuseppe Sinigaglia', city: 'Como', seats: ['#1f5ba8', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'COMO', sky: 'day', features: [] },
    },
    {
      id: 'it_cre',
      name: 'Cremonese',
      short: 'CRE',
      kit:  { shirt: '#c8102e', alt2: '#9a9a9a', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#c8102e', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Audero', 'Pezzella', 'Baschirotto', 'Bianchetti', 'Barbieri', 'Vandeputte', 'Bondo', 'Payero', 'Zerbin', 'Vardy', 'Bonazzoli'],
      stadium: { name: 'Stadio Giovanni Zini', city: 'Cremona', seats: ['#c8102e', '#9a9a9a'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'CREMONESE', sky: 'night', features: [] },
    },
    {
      id: 'it_fio',
      name: 'Fiorentina',
      short: 'FIO',
      kit:  { shirt: '#5b2b82', alt2: '#ffffff', pattern: 'plain', shorts: '#5b2b82' },
      away: { shirt: '#ffffff', alt2: '#5b2b82', pattern: 'plain', shorts: '#ffffff' },
      squad: ['De Gea', 'Gosens', 'Ranieri', 'Pongračić', 'Dodô', 'Ndour', 'Mandragora', 'Fagioli', 'Sohm', 'Kean', 'Gudmundsson'],
      stadium: { name: 'Stadio Artemio Franchi', city: 'Florencia', seats: ['#5b2b82', '#ffffff'], track: '#c8552c', roof: null, shape: 'rect', mow: 'stripes', letters: 'VIOLA', sky: 'night', features: ['tower'] },
    },
    {
      id: 'it_gen',
      name: 'Genoa',
      short: 'GEN',
      kit:  { shirt: '#a6192e', alt2: '#002d62', pattern: 'stripes', shorts: '#002d62' },
      away: { shirt: '#ffffff', alt2: '#a6192e', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Leali', 'Martín', 'Vásquez', 'Østigård', 'Norton-Cuffy', 'Ellertsson', 'Frendrup', 'Malinovskyi', 'Thorsby', 'Colombo', 'Vitinha'],
      stadium: { name: 'Stadio Luigi Ferraris', city: 'Génova', seats: ['#a6192e', '#002d62'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'GRIFONE', sky: 'night', features: [] },
    },
    {
      id: 'it_hel',
      name: 'Hellas Verona',
      short: 'HEL',
      kit:  { shirt: '#003b7e', alt2: '#ffd200', pattern: 'plain', shorts: '#003b7e' },
      away: { shirt: '#ffd200', alt2: '#003b7e', pattern: 'plain', shorts: '#ffd200' },
      squad: ['Montipò', 'Frese', 'Bella-Kotchap', 'Nelsson', 'Belghali', 'Harroui', 'Gagliardini', 'Serdar', 'Bernede', 'Orban', 'Giovane'],
      stadium: { name: 'Stadio Marcantonio Bentegodi', city: 'Verona', seats: ['#003b7e', '#ffd200'], track: '#c8552c', roof: null, shape: 'round', mow: 'stripes', letters: 'HELLAS', sky: 'night', features: [] },
    },
    {
      id: 'it_laz',
      name: 'Lazio',
      short: 'LAZ',
      kit:  { shirt: '#87d8f7', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#14213d', alt2: '#87d8f7', pattern: 'plain', shorts: '#14213d' },
      squad: ['Provedel', 'Tavares', 'Romagnoli', 'Gila', 'Marušić', 'Zaccagni', 'Guendouzi', 'Rovella', 'Isaksen', 'Castellanos', 'Dia'],
      stadium: { name: 'Stadio Olimpico', city: 'Roma', seats: ['#87d8f7', '#ffffff'], track: '#c8552c', roof: null, shape: 'round', mow: 'stripes', letters: 'LAZIO', sky: 'night', features: [] },
    },
    {
      id: 'it_lec',
      name: 'Lecce',
      short: 'LEC',
      kit:  { shirt: '#ffe500', alt2: '#d40000', pattern: 'stripes', shorts: '#d40000' },
      away: { shirt: '#ffffff', alt2: '#d40000', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Falcone', 'Gallo', 'Gaspar', 'Gabriel', 'Veiga', 'Banda', 'Coulibaly', 'Ramadani', 'Morente', 'Štulić', 'Pierotti'],
      stadium: { name: 'Stadio Via del Mare', city: 'Lecce', seats: ['#ffe500', '#d40000'], track: '#c8552c', roof: null, shape: 'rect', mow: 'stripes', letters: 'LECCE', sky: 'dusk', features: [] },
    },
    {
      id: 'it_prm',
      name: 'Parma',
      short: 'PRM',
      kit:  { shirt: '#ffffff', alt2: '#000000', pattern: 'center', shorts: '#000000' },
      away: { shirt: '#ffd400', alt2: '#1b3c8a', pattern: 'hoops', shorts: '#1b3c8a' },
      squad: ['Suzuki', 'Valeri', 'Circati', 'Delprato', 'Britschgi', 'Bernabé', 'Keita', 'Sørensen', 'Ondrejka', 'Pellegrino', 'Cutrone'],
      stadium: { name: 'Stadio Ennio Tardini', city: 'Parma', seats: ['#ffd400', '#1b3c8a'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'PARMA', sky: 'night', features: [] },
    },
    {
      id: 'it_pis',
      name: 'Pisa',
      short: 'PIS',
      kit:  { shirt: '#000000', alt2: '#004ea3', pattern: 'stripes', shorts: '#000000' },
      away: { shirt: '#ffffff', alt2: '#004ea3', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Scuffet', 'Angori', 'Canestrelli', 'Caracciolo', 'Touré', 'Leris', 'Aebischer', 'Marin', 'Tramoni', 'Nzola', 'Moreo'],
      stadium: { name: 'Arena Garibaldi', city: 'Pisa', seats: ['#004ea3', '#000000'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'PISA', sky: 'night', features: ['tower'] },
    },
    {
      id: 'it_sas',
      name: 'Sassuolo',
      short: 'SAS',
      kit:  { shirt: '#00a752', alt2: '#000000', pattern: 'stripes', shorts: '#000000' },
      away: { shirt: '#ffffff', alt2: '#00a752', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Muric', 'Doig', 'Muharemović', 'Idzes', 'Walukiewicz', 'Laurienté', 'Matić', 'Koné', 'Berardi', 'Pinamonti', 'Thorstvedt'],
      stadium: { name: 'Mapei Stadium', city: 'Reggio Emilia', seats: ['#00a752', '#000000'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'NEROVERDI', sky: 'night', features: [] },
    },
    {
      id: 'it_tor',
      name: 'Torino',
      short: 'TOR',
      kit:  { shirt: '#8a1e03', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#8a1e03', pattern: 'sash', shorts: '#8a1e03' },
      squad: ['Israel', 'Biraghi', 'Coco', 'Maripán', 'Pedersen', 'Vlašić', 'Ilić', 'Asllani', 'Lazaro', 'Simeone', 'Adams'],
      stadium: { name: 'Stadio Olimpico Grande Torino', city: 'Turín', seats: ['#8a1e03', '#ffffff'], track: '#c8552c', roof: null, shape: 'rect', mow: 'stripes', letters: 'TORO', sky: 'night', features: [] },
    },
    {
      id: 'it_udi',
      name: 'Udinese',
      short: 'UDI',
      kit:  { shirt: '#000000', alt2: '#ffffff', pattern: 'stripes', shorts: '#000000' },
      away: { shirt: '#ffffff', alt2: '#000000', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Okoye', 'Kamara', 'Solet', 'Kristensen', 'Zanoli', 'Atta', 'Karlström', 'Ekkelenkamp', 'Zaniolo', 'Davis', 'Bayo'],
      stadium: { name: 'Bluenergy Stadium', city: 'Udine', seats: ['#000000', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'UDINESE', sky: 'night', features: ['arch'] },
    },
  ],
};
