// J1 League 2026-27 (primera temporada con calendario europeo)
export default {
  id: 'jp',
  name: 'J1 League',
  country: 'Japón',
  // Todos los equipos de la máxima categoría, en orden alfabético por nombre.
  teams: ['jp_avi', 'jp_cer', 'jp_fag', 'jp_fct', 'jp_gam', 'jp_jef', 'jp_kas', 'jp_kre', 'jp_kaw', 'jp_kyo', 'jp_mac', 'jp_mit', 'jp_nag', 'jp_san', 'jp_shi', 'jp_ver', 'jp_ura', 'jp_vvn', 'jp_kob', 'jp_yfm'],
  // Equipos que no existían en el juego.
  newTeams: [
    {
      id: 'jp_avi',
      name: 'Avispa Fukuoka',
      short: 'AVI',
      kit: { shirt: '#0b2350', alt2: '#c0c6cf', pattern: 'plain', shorts: '#0b2350' },
      away: { shirt: '#ffffff', alt2: '#0b2350', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Obata', 'Yuzawa', 'Nara', 'Kamijima', 'Miki', 'Jogo', 'Shigemi', 'Matsuoka', 'Okuno', 'Zahedi', 'Ben Khalifa'],
      stadium: { name: 'Best Denki Stadium', city: 'Fukuoka', seats: ['#0b2350', '#c0c6cf'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'AVISPA', sky: 'night', features: [] },
    },
    {
      id: 'jp_cer',
      name: 'Cerezo Osaka',
      short: 'CER',
      kit: { shirt: '#e8508a', alt2: '#1a2a5a', pattern: 'plain', shorts: '#1a2a5a' },
      away: { shirt: '#ffffff', alt2: '#e8508a', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Kambayashi', 'Okuda', 'Hatanaka', 'Inoue', 'Takahashi', 'Lucas Fernandes', 'Kagawa', 'Tanaka', 'Shibayama', 'Sakuragawa', 'Andrade'],
      stadium: { name: 'Yodoko Sakura Stadium', city: 'Osaka', seats: ['#e8508a', '#1a2a5a'], track: null, roof: '#5d636c', shape: 'rect', mow: 'stripes', letters: 'CEREZO', sky: 'night', features: [] },
    },
    {
      id: 'jp_fag',
      name: 'Fagiano Okayama',
      short: 'FAG',
      kit: { shirt: '#a6192e', alt2: '#0b2350', pattern: 'plain', shorts: '#0b2350' },
      away: { shirt: '#ffffff', alt2: '#a6192e', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Moser', 'Suzuki', 'Tagami', 'Omori', 'Motoyama', 'Esaka', 'Takeuchi', 'Tabei', 'Fujita', 'Lucão', 'Leo Gaúcho'],
      stadium: { name: 'JFE Harenokuni Stadium', city: 'Okayama', seats: ['#a6192e', '#f2f2f2'], track: '#c8552c', roof: null, shape: 'round', mow: 'stripes', letters: 'FAGIANO', sky: 'day', features: [] },
    },
    {
      id: 'jp_fct',
      name: 'FC Tokyo',
      short: 'TOK',
      kit: { shirt: '#0b3fa8', alt2: '#d1162b', pattern: 'stripes', shorts: '#0b2350' },
      away: { shirt: '#ffffff', alt2: '#0b3fa8', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Kim Seung-gyu', 'Bangnagande', 'Morishige', 'Scholz', 'Muroya', 'Sato', 'Ko', 'Hashimoto', 'Tawaratsumida', 'Marcelo Ryan', 'Nagakura'],
      stadium: { name: 'Ajinomoto Stadium', city: 'Tokio', seats: ['#0b3fa8', '#d1162b'], track: '#c8552c', roof: '#c9ced6', shape: 'round', mow: 'stripes', letters: 'TOKYO', sky: 'night', features: [] },
    },
    {
      id: 'jp_gam',
      name: 'Gamba Osaka',
      short: 'GAM',
      kit: { shirt: '#0b3fa8', alt2: '#111111', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#0b3fa8', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Ichimori', 'Hatsuse', 'Nakatani', 'Fukuoka', 'Handa', 'Welton', 'Abe', 'Kurata', 'Yamashita', 'Usami', 'Jebali'],
      stadium: { name: 'Panasonic Stadium Suita', city: 'Suita', seats: ['#0b3fa8', '#1a1a1a'], track: null, roof: '#c9ced6', shape: 'rect', mow: 'stripes', letters: 'GAMBA', sky: 'night', features: [] },
    },
    {
      id: 'jp_jef',
      name: 'JEF United Chiba',
      short: 'JEF',
      kit: { shirt: '#ffe100', alt2: '#00843d', pattern: 'plain', shorts: '#00843d' },
      away: { shirt: '#ffffff', alt2: '#00843d', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Suárez', 'Toriumi', 'Kuboniwa', 'Suzuki', 'Kawano', 'Tsubaki', 'Taguchi', 'Kobayashi', 'Himeno', 'Ishikawa', 'Erison'],
      stadium: { name: 'Fukuda Denshi Arena', city: 'Chiba', seats: ['#ffe100', '#00843d'], track: null, roof: '#c9ced6', shape: 'rect', mow: 'stripes', letters: 'JEF UNITED', sky: 'night', features: [] },
    },
    {
      id: 'jp_kas',
      name: 'Kashima Antlers',
      short: 'KAS',
      kit: { shirt: '#b0102a', alt2: '#0b1e5a', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#b0102a', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Hayakawa', 'Anzai', 'Ueda', 'Kim Tae-hyeon', 'Chida', 'Élber', 'Misao', 'Shibasaki', 'Higuchi', 'Suzuki', 'Léo Ceará'],
      stadium: { name: 'Mercari Stadium', city: 'Kashima', seats: ['#b0102a', '#0b1e5a'], track: null, roof: '#c9ced6', shape: 'rect', mow: 'stripes', letters: 'ANTLERS', sky: 'night', features: [] },
    },
    {
      id: 'jp_kre',
      name: 'Kashiwa Reysol',
      short: 'KRE',
      kit: { shirt: '#fde100', alt2: '#111111', pattern: 'plain', shorts: '#111111' },
      away: { shirt: '#111111', alt2: '#fde100', pattern: 'plain', shorts: '#111111' },
      squad: ['Saruta', 'Mitsumaru', 'Inukai', 'Koga', 'Harada', 'Kubo', 'Segawa', 'Kumasaka', 'Nakagawa', 'Hosoya', 'Kakita'],
      stadium: { name: 'Sankyo Frontier Kashiwa Stadium', city: 'Kashiwa', seats: ['#fde100', '#1a1a1a'], track: null, roof: '#5d636c', shape: 'rect', mow: 'stripes', letters: 'REYSOL', sky: 'night', features: [] },
    },
    {
      id: 'jp_kaw',
      name: 'Kawasaki Frontale',
      short: 'KAW',
      kit: { shirt: '#3fa6dd', alt2: '#111111', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#3fa6dd', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Brodersen', 'Miura', 'Uremović', 'Sasaki', 'Romano', 'Tachibanada', 'Oshima', 'Wakizaka', 'Ito', 'Romanić', 'Kobayashi'],
      stadium: { name: 'Todoroki Stadium', city: 'Kawasaki', seats: ['#3fa6dd', '#1a1a1a'], track: '#c8552c', roof: '#c9ced6', shape: 'round', mow: 'stripes', letters: 'FRONTALE', sky: 'night', features: [] },
    },
    {
      id: 'jp_kyo',
      name: 'Kyoto Sanga',
      short: 'KYO',
      kit: { shirt: '#5a2a82', alt2: '#ffffff', pattern: 'plain', shorts: '#5a2a82' },
      away: { shirt: '#ffffff', alt2: '#5a2a82', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Ota', 'Sumida', 'Miyamoto', 'Suzuki', 'Fukuda', 'Okugawa', 'Kawasaki', 'Fukuoka', 'João Pedro', 'Rafael Elias', 'Marco Túlio'],
      stadium: { name: 'Sanga Stadium by Kyocera', city: 'Kameoka', seats: ['#5a2a82', '#f2f2f2'], track: null, roof: '#c9ced6', shape: 'rect', mow: 'stripes', letters: 'SANGA', sky: 'day', features: [] },
    },
    {
      id: 'jp_mac',
      name: 'Machida Zelvia',
      short: 'MAC',
      kit: { shirt: '#0b2a6a', alt2: '#c9a227', pattern: 'plain', shorts: '#0b2a6a' },
      away: { shirt: '#ffffff', alt2: '#0b2a6a', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Tani', 'Nakayama', 'Drešević', 'Shoji', 'Mochizuki', 'Soma', 'Shimoda', 'Sento', 'Nishimura', 'Fujio', 'Duke'],
      stadium: { name: 'Machida GION Stadium', city: 'Machida', seats: ['#0b2a6a', '#f2f2f2'], track: '#c8552c', roof: null, shape: 'round', mow: 'stripes', letters: 'ZELVIA', sky: 'day', features: [] },
    },
    {
      id: 'jp_mit',
      name: 'Mito HollyHock',
      short: 'MIT',
      kit: { shirt: '#0d3b8c', alt2: '#ffffff', pattern: 'plain', shorts: '#0d3b8c' },
      away: { shirt: '#ffffff', alt2: '#0d3b8c', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Nishikawa', 'Ieizumi', 'Itakura', 'Omori', 'Kimoto', 'Osaki', 'Kato', 'Arai', 'Yamamoto', 'Watanabe', 'Tada'],
      stadium: { name: 'K\'s denki Stadium Mito', city: 'Mito', seats: ['#0d3b8c', '#f2f2f2'], track: '#c8552c', roof: null, shape: 'round', mow: 'stripes', letters: 'HOLLYHOCK', sky: 'day', features: [] },
    },
    {
      id: 'jp_nag',
      name: 'Nagoya Grampus',
      short: 'NAG',
      kit: { shirt: '#d1162b', alt2: '#c9a227', pattern: 'plain', shorts: '#d1162b' },
      away: { shirt: '#ffffff', alt2: '#d1162b', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Schmidt', 'Tokumoto', 'Sato', 'Nogami', 'Hara', 'Nakayama', 'Inagaki', 'Koyamatsu', 'Morishima', 'Mateus', 'Yamagishi'],
      stadium: { name: 'Toyota Stadium', city: 'Toyota', seats: ['#d1162b', '#f2f2f2'], track: null, roof: '#5d636c', shape: 'rect', mow: 'stripes', letters: 'GRAMPUS', sky: 'night', features: [] },
    },
    {
      id: 'jp_san',
      name: 'Sanfrecce Hiroshima',
      short: 'HIR',
      kit: { shirt: '#4b2a87', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#4b2a87', pattern: 'plain', shorts: '#4b2a87' },
      squad: ['Osako', 'Shiotani', 'Araki', 'Sasaki', 'Nakano', 'Higashi', 'Kawabe', 'Matsumoto', 'Kato', 'Suzuki', 'Haller'],
      stadium: { name: 'Edion Peace Wing', city: 'Hiroshima', seats: ['#4b2a87', '#f2f2f2'], track: null, roof: '#c9ced6', shape: 'rect', mow: 'stripes', letters: 'SANFRECCE', sky: 'dusk', features: [] },
    },
    {
      id: 'jp_shi',
      name: 'Shimizu S-Pulse',
      short: 'SHI',
      kit: { shirt: '#f5821f', alt2: '#0b2350', pattern: 'plain', shorts: '#f5821f' },
      away: { shirt: '#ffffff', alt2: '#f5821f', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Umeda', 'Yoshida', 'Sumiyoshi', 'Takahashi', 'Hasukawa', 'Capixaba', 'Dieguinho', 'Won Du-jae', 'Matsuzaki', 'Kitagawa', 'Oh Se-hun'],
      stadium: { name: 'IAI Stadium Nihondaira', city: 'Shizuoka', seats: ['#f5821f', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'SPULSE', sky: 'day', features: [] },
    },
    {
      id: 'jp_ver',
      name: 'Tokyo Verdy',
      short: 'VER',
      kit: { shirt: '#00843d', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#00843d', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Vidotto', 'Fukazawa', 'Hayashi', 'Taniguchi', 'Miyahara', 'Saito', 'Morita', 'Matsuhashi', 'Arai', 'Yamami', 'Someno'],
      stadium: { name: 'Ajinomoto Stadium', city: 'Tokio', seats: ['#00843d', '#f2f2f2'], track: '#c8552c', roof: '#c9ced6', shape: 'round', mow: 'stripes', letters: 'VERDY', sky: 'night', features: [] },
    },
    {
      id: 'jp_ura',
      name: 'Urawa Reds',
      short: 'URA',
      kit: { shirt: '#e60012', alt2: '#111111', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#e60012', pattern: 'plain', shorts: '#111111' },
      squad: ['Nishikawa', 'Nemoto', 'Boza', 'Miyamoto', 'Ishihara', 'Sávio', 'Gustafson', 'Yasui', 'Watanabe', 'Matsuo', 'Thelin'],
      stadium: { name: 'Saitama Stadium 2002', city: 'Saitama', seats: ['#e60012', '#1a1a1a'], track: null, roof: '#c9ced6', shape: 'round', mow: 'stripes', letters: 'REDS', sky: 'night', features: [] },
    },
    {
      id: 'jp_vvn',
      name: 'V-Varen Nagasaki',
      short: 'VVN',
      kit: { shirt: '#f08300', alt2: '#0b3fa8', pattern: 'plain', shorts: '#0b3fa8' },
      away: { shirt: '#ffffff', alt2: '#f08300', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Goto', 'Sekiguchi', 'Eduardo', 'Shindo', 'Yoneda', 'Sawada', 'Pituca', 'Yamaguchi', 'Matsumoto', 'Santana', 'Yamasaki'],
      stadium: { name: 'Peace Stadium', city: 'Nagasaki', seats: ['#f08300', '#0b3fa8'], track: null, roof: '#c9ced6', shape: 'rect', mow: 'stripes', letters: 'VVAREN', sky: 'dusk', features: [] },
    },
    {
      id: 'jp_kob',
      name: 'Vissel Kobe',
      short: 'KOB',
      kit: { shirt: '#8a1538', alt2: '#111111', pattern: 'plain', shorts: '#8a1538' },
      away: { shirt: '#ffffff', alt2: '#8a1538', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Maekawa', 'Nagato', 'Thuler', 'Yamakawa', 'Sakai', 'Iino', 'Ogihara', 'Ideguchi', 'Ide', 'Osako', 'Muto'],
      stadium: { name: 'Noevir Stadium Kobe', city: 'Kobe', seats: ['#8a1538', '#1a1a1a'], track: null, roof: '#5d636c', shape: 'rect', mow: 'stripes', letters: 'VISSEL', sky: 'night', features: [] },
    },
    {
      id: 'jp_yfm',
      name: 'Yokohama F. Marinos',
      short: 'YFM',
      kit: { shirt: '#1d3e8a', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#1d3e8a', pattern: 'plain', shorts: '#1d3e8a' },
      squad: ['Park Il-gyu', 'Suwama', 'Tsunoda', 'Quiñones', 'Matsubara', 'Amano', 'Kida', 'Yamane', 'Miyaichi', 'Croux', 'Onaiwu'],
      stadium: { name: 'Nissan Stadium', city: 'Yokohama', seats: ['#1d3e8a', '#d1162b'], track: '#c8552c', roof: '#c9ced6', shape: 'round', mow: 'stripes', letters: 'MARINOS', sky: 'night', features: [] },
    },
  ],
};
