// Liga MX Apertura 2025 (temporada 2025-26)
export default {
  id: 'mx',
  name: 'Liga MX',
  country: 'México',
  // Todos los equipos de la máxima categoría, en orden alfabético por nombre.
  teams: ['ame', 'mx_ats', 'mx_asl', 'mx_caz', 'mx_fcj', 'mx_chv', 'mx_leo', 'mx_maz', 'mx_mty', 'mx_nec', 'mx_pch', 'mx_pub', 'mx_pum', 'mx_qro', 'mx_sla', 'mx_tig', 'mx_xol', 'mx_tol'],
  // Equipos que no existían en el juego.
  newTeams: [
    {
      id: 'mx_ats',
      name: 'Atlas',
      short: 'ATS',
      kit: { shirt: '#c8102e', alt2: '#111111', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#c8102e', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Vargas', 'Gómez', 'Capasso', 'Schlegel', 'Santamaría', 'Ramírez', 'Rocha', 'González', 'Herrera', 'Aguirre', 'Djurdjevic'],
      stadium: { name: 'Estadio Jalisco', city: 'Guadalajara', seats: ['#c8102e', '#1a1a1a'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'ROJINEGROS', sky: 'night', features: [] },
    },
    {
      id: 'mx_asl',
      name: 'Atlético San Luis',
      short: 'ASL',
      kit: { shirt: '#d1162b', alt2: '#0b2c7a', pattern: 'plain', shorts: '#0b2c7a' },
      away: { shirt: '#ffffff', alt2: '#d1162b', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Sánchez', 'Bilbao', 'García', 'Murillo', 'Chávez', 'Hernández', 'Salles', 'Macías', 'Galdames', 'Leone', 'João Pedro'],
      stadium: { name: 'Estadio Alfonso Lastras', city: 'San Luis Potosí', seats: ['#d1162b', '#0b2c7a'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'SAN LUIS', sky: 'night', features: [] },
    },
    {
      id: 'mx_caz',
      name: 'Cruz Azul',
      short: 'CAZ',
      kit: { shirt: '#0b4ea2', alt2: '#ffffff', pattern: 'plain', shorts: '#0b4ea2' },
      away: { shirt: '#ffffff', alt2: '#0b4ea2', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Mier', 'Orozco', 'Ditta', 'Piovi', 'Sánchez', 'Paradela', 'Lira', 'Romero', 'Rotondi', 'Sepúlveda', 'Fernández'],
      stadium: { name: 'Estadio Olímpico Universitario', city: 'Ciudad de México', seats: ['#0b4ea2', '#f2f2f2'], track: '#c8552c', roof: null, shape: 'round', mow: 'stripes', letters: 'LA MAQUINA', sky: 'night', features: [] },
    },
    {
      id: 'mx_fcj',
      name: 'FC Juárez',
      short: 'FCJ',
      kit: { shirt: '#d1162b', alt2: '#00843d', pattern: 'plain', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#d1162b', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Jurado', 'Cerda', 'García', 'Ramírez', 'Salas', 'Zaldívar', 'Mendoza', 'Ponce', 'Madson', 'Estupiñán', 'Pérez'],
      stadium: { name: 'Estadio Olímpico Benito Juárez', city: 'Ciudad Juárez', seats: ['#d1162b', '#00843d'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'BRAVOS', sky: 'dusk', features: [] },
    },
    {
      id: 'mx_chv',
      name: 'Guadalajara',
      short: 'CHV',
      kit: { shirt: '#d8132b', alt2: '#ffffff', pattern: 'stripes', shorts: '#0b2c5a' },
      away: { shirt: '#0b2c5a', alt2: '#d8132b', pattern: 'plain', shorts: '#0b2c5a' },
      squad: ['Rangel', 'Mozo', 'Sepúlveda', 'Castillo', 'Ledezma', 'Cowell', 'Romo', 'F. González', 'Alvarado', 'A. González', 'Pulido'],
      stadium: { name: 'Estadio Akron', city: 'Zapopan', seats: ['#d8132b', '#0b2c5a'], track: null, roof: '#5d636c', shape: 'round', mow: 'stripes', letters: 'CHIVAS', sky: 'night', features: [] },
    },
    {
      id: 'mx_leo',
      name: 'León',
      short: 'LEO',
      kit: { shirt: '#00703c', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#00703c', pattern: 'plain', shorts: '#00703c' },
      squad: ['Jiménez', 'Frías', 'Barreiro', 'Bellón', 'Tesillo', 'Ambriz', 'Rodríguez', 'Fernández', 'Alvarado', 'Díaz', 'Di Yorio'],
      stadium: { name: 'Estadio León', city: 'León', seats: ['#00703c', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'LA FIERA', sky: 'night', features: [] },
    },
    {
      id: 'mx_maz',
      name: 'Mazatlán',
      short: 'MAZ',
      kit: { shirt: '#5b2a86', alt2: '#ffffff', pattern: 'plain', shorts: '#5b2a86' },
      away: { shirt: '#ffffff', alt2: '#5b2a86', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Gutiérrez', 'Lima', 'Ramírez', 'Vargas', 'Bernal', 'Colula', 'Benedetti', 'Sánchez', 'Rodríguez', 'Gomes', 'Ortiz'],
      stadium: { name: 'Estadio El Encanto', city: 'Mazatlán', seats: ['#5b2a86', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'MAZATLAN', sky: 'dusk', features: [] },
    },
    {
      id: 'mx_mty',
      name: 'Monterrey',
      short: 'MTY',
      kit: { shirt: '#0b2c5a', alt2: '#ffffff', pattern: 'stripes', shorts: '#0b2c5a' },
      away: { shirt: '#ffffff', alt2: '#0b2c5a', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Andrada', 'Arteaga', 'Ramos', 'Guzmán', 'Medina', 'Ocampos', 'Ambriz', 'Canales', 'Rodríguez', 'Martial', 'Berterame'],
      stadium: { name: 'Estadio BBVA', city: 'Guadalupe', seats: ['#0b2c5a', '#8f939b'], track: null, roof: '#a3a9b1', shape: 'rect', mow: 'stripes', letters: 'RAYADOS', sky: 'night', features: [] },
    },
    {
      id: 'mx_nec',
      name: 'Necaxa',
      short: 'NEC',
      kit: { shirt: '#d1162b', alt2: '#ffffff', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#111111', alt2: '#d1162b', pattern: 'plain', shorts: '#111111' },
      squad: ['Unsain', 'Pérez', 'Oliveros', 'Peralta', 'Rodríguez', 'Garnica', 'Medina', 'Gómez', 'Esquivel', 'Monreal', 'Badaloni'],
      stadium: { name: 'Estadio Victoria', city: 'Aguascalientes', seats: ['#d1162b', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'RAYOS', sky: 'night', features: [] },
    },
    {
      id: 'mx_pch',
      name: 'Pachuca',
      short: 'PCH',
      kit: { shirt: '#ffffff', alt2: '#0b2c5a', pattern: 'stripes', shorts: '#0b2c5a' },
      away: { shirt: '#0b2c5a', alt2: '#ffffff', pattern: 'plain', shorts: '#0b2c5a' },
      squad: ['Moreno', 'González', 'Barreto', 'Bauermann', 'Rodríguez', 'Kenedy', 'Pedraza', 'Montiel', 'Idrissi', 'Hinestroza', 'Rondón'],
      stadium: { name: 'Estadio Hidalgo', city: 'Pachuca', seats: ['#0b2c5a', '#f2f2f2'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'TUZOS', sky: 'night', features: [] },
    },
    {
      id: 'mx_pub',
      name: 'Puebla',
      short: 'PUB',
      kit: { shirt: '#ffffff', alt2: '#1d3e8a', pattern: 'sash', shorts: '#1d3e8a' },
      away: { shirt: '#1d3e8a', alt2: '#ffffff', pattern: 'sash', shorts: '#1d3e8a' },
      squad: ['Rodríguez', 'Silva', 'Ferrareis', 'Navarro', 'Orrantia', 'Parra', 'Esquivel', 'De Buen', 'Cavallini', 'Zaldívar', 'Fernández'],
      stadium: { name: 'Estadio Cuauhtémoc', city: 'Puebla', seats: ['#1d3e8a', '#f2f2f2'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'LA FRANJA', sky: 'night', features: [] },
    },
    {
      id: 'mx_pum',
      name: 'Pumas UNAM',
      short: 'PUM',
      kit: { shirt: '#ffffff', alt2: '#0b2c5a', pattern: 'plain', shorts: '#0b2c5a' },
      away: { shirt: '#0b2c5a', alt2: '#c9a227', pattern: 'plain', shorts: '#0b2c5a' },
      squad: ['Navas', 'Duarte', 'Magallán', 'Silva', 'Bennevendo', 'Ruvalcaba', 'Carrasquilla', 'Vite', 'Medina', 'Martínez', 'Juninho'],
      stadium: { name: 'Estadio Olímpico Universitario', city: 'Ciudad de México', seats: ['#0b2c5a', '#c9a227'], track: '#c8552c', roof: null, shape: 'round', mow: 'stripes', letters: 'PUMAS', sky: 'day', features: [] },
    },
    {
      id: 'mx_qro',
      name: 'Querétaro',
      short: 'QRO',
      kit: { shirt: '#1d3e8a', alt2: '#111111', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#1d3e8a', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Allison', 'Barrera', 'Venegas', 'Mendoza', 'Ramos', 'Sanabria', 'Escoboza', 'Rojas', 'Coronel', 'Lozano', 'Ríos'],
      stadium: { name: 'Estadio Corregidora', city: 'Querétaro', seats: ['#1d3e8a', '#1a1a1a'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'GALLOS', sky: 'night', features: [] },
    },
    {
      id: 'mx_sla',
      name: 'Santos Laguna',
      short: 'SLA',
      kit: { shirt: '#00843d', alt2: '#ffffff', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#111111', alt2: '#00843d', pattern: 'plain', shorts: '#111111' },
      squad: ['Acevedo', 'Hernández', 'Doria', 'Amione', 'Prieto', 'Villarreal', 'Rivera', 'Lozano', 'Sordo', 'Cervantes', 'Preciado'],
      stadium: { name: 'Estadio Corona', city: 'Torreón', seats: ['#00843d', '#f2f2f2'], track: null, roof: '#c9ced6', shape: 'rect', mow: 'stripes', letters: 'GUERREROS', sky: 'night', features: [] },
    },
    {
      id: 'mx_tig',
      name: 'Tigres UANL',
      short: 'UANL',
      kit: { shirt: '#f7b500', alt2: '#0b2c5a', pattern: 'plain', shorts: '#0b2c5a' },
      away: { shirt: '#0b2c5a', alt2: '#f7b500', pattern: 'plain', shorts: '#0b2c5a' },
      squad: ['Guzmán', 'Angulo', 'Joaquim', 'Purata', 'Aquino', 'Lainez', 'Gorriarán', 'Brunetta', 'Correa', 'Gignac', 'Herrera'],
      stadium: { name: 'Estadio Universitario', city: 'San Nicolás de los Garza', seats: ['#f7b500', '#0b2c5a'], track: null, roof: null, shape: 'round', mow: 'stripes', letters: 'EL VOLCAN', sky: 'night', features: [] },
    },
    {
      id: 'mx_xol',
      name: 'Tijuana',
      short: 'XOL',
      kit: { shirt: '#c8102e', alt2: '#111111', pattern: 'plain', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#c8102e', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Rodríguez', 'Fernández', 'Barbosa', 'Montes', 'Rivera', 'Castañeda', 'Mora', 'Martínez', 'Ramírez', 'Delgado', 'Vázquez'],
      stadium: { name: 'Estadio Caliente', city: 'Tijuana', seats: ['#c8102e', '#1a1a1a'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'XOLOS', sky: 'night', features: [] },
    },
    {
      id: 'mx_tol',
      name: 'Toluca',
      short: 'TOL',
      kit: { shirt: '#d1162b', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#d1162b', pattern: 'plain', shorts: '#d1162b' },
      squad: ['González', 'Gallardo', 'Pereira', 'Méndez', 'Briseño', 'Vega', 'Ruiz', 'Romero', 'Helinho', 'Angulo', 'Paulinho'],
      stadium: { name: 'Estadio Nemesio Díez', city: 'Toluca', seats: ['#d1162b', '#f2f2f2'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'DIABLOS ROJOS', sky: 'day', features: [] },
    },
  ],
};
