// Primeira Liga 2025-26
export default {
  id: 'pt',
  name: 'Primeira Liga',
  country: 'Portugal',
  // Todos los equipos de la máxima categoría, en orden alfabético por nombre.
  teams: [
    'pt_alv', 'pt_aro', 'pt_avs', 'ben', 'pt_bra', 'pt_cpa', 'pt_esl', 'pt_eam', 'pt_fam',
    'pt_gil', 'pt_mor', 'pt_nac', 'fcp', 'pt_rav', 'pt_stc', 'scp', 'pt_ton', 'pt_vsc',
  ],
  // Equipos que no existían en el juego.
  newTeams: [
    {
      id: 'pt_alv', name: 'Alverca', short: 'ALV',
      kit:  { shirt: '#d71920', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#d71920', pattern: 'plain', shorts: '#d71920' },
      squad: ['Mendes', 'Lincoln', 'Bastos', 'Sergi Gómez', 'Davy Gui', 'Figueiredo', 'Baseya', 'Marezi', 'Chiquinho', 'Sandro Lima', 'Nabil'],
      stadium: { name: 'Complexo do FC Alverca', city: 'Alverca do Ribatejo', seats: ['#d71920', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'ALVERCA', sky: 'day', features: [] },
    },
    {
      id: 'pt_aro', name: 'Arouca', short: 'ARO',
      kit:  { shirt: '#f7d117', alt2: '#0b3d91', pattern: 'plain', shorts: '#0b3d91' },
      away: { shirt: '#0b3d91', alt2: '#f7d117', pattern: 'plain', shorts: '#0b3d91' },
      squad: ['Mantl', 'Fontán', 'Popovic', 'Chico Lamba', 'Esgaio', 'Pedro Santos', 'Fukui', 'David Simão', 'Trezza', 'Barbero', 'Lee Hyun-ju'],
      stadium: { name: 'Estádio Municipal de Arouca', city: 'Arouca', seats: ['#f7d117', '#0b3d91'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'AROUCA', sky: 'day', features: [] },
    },
    {
      id: 'pt_avs', name: 'AVS', short: 'AVS',
      kit:  { shirt: '#d71920', alt2: '#ffffff', pattern: 'sleeves', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#d71920', pattern: 'plain', shorts: '#d71920' },
      squad: ['Simão', 'Devenish', 'Aderllan', 'Abascal', 'Roux', 'Lucas Piazón', 'Jaume Grau', 'Tunde', 'Nené', 'John Mercado', 'Guillermo'],
      stadium: { name: 'Estádio do CD Aves', city: 'Vila das Aves', seats: ['#d71920', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'AVS', sky: 'night', features: [] },
    },
    {
      id: 'pt_bra', name: 'Braga', short: 'SCB',
      kit:  { shirt: '#d7182a', alt2: '#ffffff', pattern: 'sleeves', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#d7182a', pattern: 'plain', shorts: '#d7182a' },
      squad: ['Hornicek', 'Lelo', 'P. Oliveira', 'Niakaté', 'Víctor Gómez', 'Horta', 'Moutinho', 'Gorby', 'Zalazar', 'El Ouazzani', 'Pau Víctor'],
      stadium: { name: 'Estádio Municipal de Braga', city: 'Braga', seats: ['#d7182a', '#ffffff'], track: null, roof: '#d9d9d9', shape: 'rect', mow: 'stripes', letters: 'BRAGA', sky: 'night', features: [] },
    },
    {
      id: 'pt_cpa', name: 'Casa Pia', short: 'CPI',
      kit:  { shirt: '#111111', alt2: '#ffffff', pattern: 'plain', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#111111', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Sequeira', 'Benaissa', 'Tchamba', 'Abou Ba', 'Larrazabal', 'Nsona', 'Scholze', 'P. Roberto', 'Livolant', 'Cassiano', 'Kaly'],
      stadium: { name: 'Estádio Pina Manique', city: 'Lisboa', seats: ['#111111', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'CASA PIA', sky: 'night', features: [] },
    },
    {
      id: 'pt_esl', name: 'Estoril', short: 'GDE',
      kit:  { shirt: '#f7d117', alt2: '#0b3d91', pattern: 'stripes', shorts: '#0b3d91' },
      away: { shirt: '#0b3d91', alt2: '#f7d117', pattern: 'plain', shorts: '#0b3d91' },
      squad: ['Joel Robles', 'Pedro Amaral', 'Bacher', 'Pedro Álvaro', 'Ricard', 'Guitane', 'Holsgrove', 'Orellana', 'J. Carvalho', 'Begraoui', 'Marqués'],
      stadium: { name: 'Estádio António Coimbra da Mota', city: 'Estoril', seats: ['#f7d117', '#0b3d91'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'ESTORIL', sky: 'dusk', features: [] },
    },
    {
      id: 'pt_eam', name: 'Estrela da Amadora', short: 'CFE',
      kit:  { shirt: '#d71920', alt2: '#0f7a3b', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#0f7a3b', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Renan', 'Bruno Langa', 'Ferro', 'Höög Jansson', 'P. Moreira', 'Jovane', 'Pinho', 'Otávio', 'Abraham', 'Kikas', 'Rodrigo'],
      stadium: { name: 'Estádio José Gomes', city: 'Amadora', seats: ['#d71920', '#0f7a3b'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'ESTRELA', sky: 'night', features: [] },
    },
    {
      id: 'pt_fam', name: 'Famalicão', short: 'FAM',
      kit:  { shirt: '#ffffff', alt2: '#0b3d91', pattern: 'plain', shorts: '#0b3d91' },
      away: { shirt: '#0b3d91', alt2: '#ffffff', pattern: 'plain', shorts: '#0b3d91' },
      squad: ['Carevic', 'Rafa Soares', 'De Haas', 'Mathias', 'R. Pinheiro', 'Sorriso', 'Gustavo Sá', 'Zabiri', 'Gil Dias', 'Elisor', 'Van de Looi'],
      stadium: { name: 'Estádio Municipal 22 de Junho', city: 'Vila Nova de Famalicão', seats: ['#0b3d91', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'FAMALICAO', sky: 'night', features: [] },
    },
    {
      id: 'pt_gil', name: 'Gil Vicente', short: 'GVF',
      kit:  { shirt: '#d7182a', alt2: '#0b3d91', pattern: 'plain', shorts: '#0b3d91' },
      away: { shirt: '#ffffff', alt2: '#d7182a', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Andrew', 'Sandro Cruz', 'Buatu', 'R. Fernandes', 'Zé Carlos', 'Murilo', 'Luís Esteves', 'Santi García', 'Joelson', 'Pablo', 'A. Moreira'],
      stadium: { name: 'Estádio Cidade de Barcelos', city: 'Barcelos', seats: ['#d7182a', '#0b3d91'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'GIL VICENTE', sky: 'night', features: [] },
    },
    {
      id: 'pt_mor', name: 'Moreirense', short: 'MOR',
      kit:  { shirt: '#00843d', alt2: '#ffffff', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#00843d', pattern: 'plain', shorts: '#00843d' },
      squad: ['Caio Secco', 'Kiko Bondoso', 'Marcelo', 'Maracás', 'Dinis Pinto', 'Alan', 'Vasco Sousa', 'Benny', 'Yan Maranhão', 'Schettine', 'G. Silva'],
      stadium: { name: 'Estádio Comendador Joaquim de Almeida Freitas', city: 'Moreira de Cónegos', seats: ['#00843d', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'MOREIRENSE', sky: 'day', features: [] },
    },
    {
      id: 'pt_nac', name: 'Nacional de Madeira', short: 'CDN',
      kit:  { shirt: '#111111', alt2: '#ffffff', pattern: 'stripes', shorts: '#111111' },
      away: { shirt: '#ffffff', alt2: '#111111', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Lucas França', 'Zé Vítor', 'José Gomes', 'Léo Santos', 'Ulisses', 'Paulinho', 'Matheus Dias', 'Daniel Penha', 'Witi', 'Ramírez', 'Chiquinho'],
      stadium: { name: 'Estádio da Madeira', city: 'Funchal', seats: ['#111111', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'NACIONAL', sky: 'day', features: [] },
    },
    {
      id: 'pt_rav', name: 'Rio Ave', short: 'RAV',
      kit:  { shirt: '#00843d', alt2: '#ffffff', pattern: 'stripes', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#00843d', pattern: 'plain', shorts: '#ffffff' },
      squad: ['Miszta', 'Ntoi', 'Petrasso', 'Brabec', 'Nikitscher', 'Pohlmann', 'Liavas', 'Blesa', 'André Luiz', 'Clayton', 'Spikic'],
      stadium: { name: 'Estádio do Rio Ave FC', city: 'Vila do Conde', seats: ['#00843d', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'RIO AVE', sky: 'night', features: [] },
    },
    {
      id: 'pt_stc', name: 'Santa Clara', short: 'STC',
      kit:  { shirt: '#d7182a', alt2: '#ffffff', pattern: 'plain', shorts: '#ffffff' },
      away: { shirt: '#ffffff', alt2: '#d7182a', pattern: 'plain', shorts: '#d7182a' },
      squad: ['G. Batista', 'MT', 'Sidney Lima', 'Luís Rocha', 'Lucas Soares', 'Klismahn', 'Firmino', 'Serginho', 'V. Lopes', 'G. Silva', 'Wendel'],
      stadium: { name: 'Estádio de São Miguel', city: 'Ponta Delgada', seats: ['#d7182a', '#ffffff'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'SANTA CLARA', sky: 'day', features: [] },
    },
    {
      id: 'pt_ton', name: 'Tondela', short: 'TON',
      kit:  { shirt: '#f7d117', alt2: '#00843d', pattern: 'stripes', shorts: '#00843d' },
      away: { shirt: '#00843d', alt2: '#f7d117', pattern: 'plain', shorts: '#00843d' },
      squad: ['B. Fontes', 'R. Alves', 'Ricardo', 'Brayan', 'Hugo Félix', 'Cícero', 'Maranhão', 'Rony Lopes', 'J. Rodríguez', 'Makan Aiko', 'Ivanovic'],
      stadium: { name: 'Estádio João Cardoso', city: 'Tondela', seats: ['#f7d117', '#00843d'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'TONDELA', sky: 'night', features: [] },
    },
    {
      id: 'pt_vsc', name: 'Vitória de Guimarães', short: 'VSC',
      kit:  { shirt: '#ffffff', alt2: '#111111', pattern: 'plain', shorts: '#111111' },
      away: { shirt: '#111111', alt2: '#ffffff', pattern: 'plain', shorts: '#111111' },
      squad: ['Charles', 'Mitrovic', 'Borevkovic', 'Villanueva', 'Nóbrega', 'T. Arcanjo', 'Tiago Silva', 'Samu', 'Gu. Silva', 'N. Oliveira', 'Ndoye'],
      stadium: { name: 'Estádio D. Afonso Henriques', city: 'Guimarães', seats: ['#ffffff', '#111111'], track: null, roof: null, shape: 'rect', mow: 'stripes', letters: 'VITORIA SC', sky: 'night', features: [] },
    },
  ],
};
